require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'
install! 'cocoapods', :deterministic_uuids => false

target 'galb' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()
# React Native Maps dependencies
rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
    
  )

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'RCTLinkingIOS',
  ]
  pod 'react-native-geocoder', :path => '../node_modules/@timwangdev/react-native-geocoder'

  target 'galbTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
